import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType

plugins {
    id("org.jetbrains.kotlin.jvm") version "2.1.21"
    id("org.jetbrains.intellij.platform") version "2.7.0"
}

group = providers.gradleProperty("pluginGroup").get()
version = providers.gradleProperty("pluginVersion").get()

kotlin {
    jvmToolchain(21)
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity(providers.gradleProperty("platformVersion"))
        pluginVerifier()
        zipSigner()
    }
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    // The IDE's own JUnit 5 session listener, which rides on the test
    // classpath with the platform, still links against JUnit 4.
    testImplementation("junit:junit:4.13.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// ---------------------------------------------------------------------------
// Build configuration. The server the plugin reports to and the directory
// under $HOME the CLI owns are one decision, made at build time and baked
// in: a release build is the only build that reaches production or the
// installed state, and it gets there by an explicit -PtokitokiRelease=true,
// never by omission. The same two values stamp the CLI bundled alongside
// (scripts/build-cli.sh), so the binary and the plugin that looks for its
// shared copy agree by construction. Same design as the VS Code extension's
// generate-build-config.js and the CLI's own Makefile.
// ---------------------------------------------------------------------------
val release = providers.gradleProperty("tokitokiRelease").map(String::toBoolean).getOrElse(false)
val baseUrl = providers.gradleProperty("tokitokiBaseUrl").getOrElse(if (release) "https://tokitoki.dev" else "http://localhost:9093")
val dataDir = providers.gradleProperty("tokitokiDataDir").getOrElse(if (release) ".tokitoki" else ".tokitoki-dev")

require(dataDir.isNotBlank() && dataDir != "." && dataDir != ".." && !dataDir.contains('/') && !dataDir.contains('\\')) {
    "tokitokiDataDir must be a single directory name, not a path: $dataDir"
}
require(baseUrl.startsWith("http://") || baseUrl.startsWith("https://")) {
    "tokitokiBaseUrl must be an http(s) URL: $baseUrl"
}

val buildConfigDir = layout.buildDirectory.dir("generated/sources/buildConfig/kotlin")
val generateBuildConfig by tasks.registering {
    inputs.property("baseUrl", baseUrl)
    inputs.property("dataDir", dataDir)
    inputs.property("version", version.toString())
    outputs.dir(buildConfigDir)
    doLast {
        val target = buildConfigDir.get().file("dev/tokitoki/jetbrains/BuildConfig.kt").asFile
        target.parentFile.mkdirs()
        target.writeText(
            """
            |// Generated by build.gradle.kts at build time. Do not edit.
            |package dev.tokitoki.jetbrains
            |
            |object BuildConfig {
            |    const val BASE_URL = "$baseUrl"
            |    const val DATA_DIR = "$dataDir"
            |    const val PLUGIN_VERSION = "$version"
            |}
            |""".trimMargin(),
        )
    }
}

sourceSets.main {
    kotlin.srcDir(generateBuildConfig)
}

// ---------------------------------------------------------------------------
// The bundled CLI: one binary per platform under resources/cli/<os>-<arch>/.
// A release build downloads the release pinned by tag and SHA-256 in
// scripts/cli-release-pins.sh. A dev build compiles the sibling
// ../tokitoki-cli checkout with dev stamps, every time, so edits there are
// picked up — a cache check would silently ship the previous build.
// ---------------------------------------------------------------------------
val cliDir = layout.buildDirectory.dir("cli")
val bundleCli by tasks.registering(Exec::class) {
    inputs.property("release", release)
    inputs.file("scripts/cli-release-pins.sh")
    outputs.dir(cliDir)
    outputs.upToDateWhen { release }
    if (release) {
        commandLine("scripts/fetch-cli-release.sh", cliDir.get().asFile.path)
    } else {
        commandLine("scripts/build-cli.sh", cliDir.get().asFile.path, baseUrl, dataDir)
    }
}

tasks.processResources {
    dependsOn(bundleCli)
    from(cliDir) { into("cli") }
}

// The newest CHANGELOG section is what the Marketplace shows as change notes.
// A tag without a section is a release nobody wrote down; fail it.
fun latestChangelogSection(): String {
    val lines = file("CHANGELOG.md").readLines()
    val start = lines.indexOfFirst { it.startsWith("## ") }
    require(start >= 0) { "CHANGELOG.md has no '## x.y.z' section" }
    val end = lines.drop(start + 1).indexOfFirst { it.startsWith("## ") }.let { if (it < 0) lines.size else start + 1 + it }
    val section = lines.subList(start, end)
    val heading = section.first().removePrefix("## ").trim()
    require(heading == version.toString()) { "CHANGELOG.md's newest section is $heading, but the plugin version is $version" }
    val items = mutableListOf<String>()
    for (line in section.drop(1)) {
        when {
            line.startsWith("- ") -> items += line.removePrefix("- ").trim()
            line.startsWith("  ") && items.isNotEmpty() -> items[items.lastIndex] = items.last() + " " + line.trim()
        }
    }
    fun escape(s: String) = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        .replace(Regex("\\*\\*(.+?)\\*\\*"), "<b>$1</b>").replace(Regex("`(.+?)`"), "<code>$1</code>")
    return "<ul>" + items.joinToString("") { "<li>${escape(it)}</li>" } + "</ul>"
}

intellijPlatform {
    pluginConfiguration {
        version = project.version.toString()
        changeNotes = provider { latestChangelogSection() }
        ideaVersion {
            sinceBuild = "242"
            untilBuild = provider { null }
        }
    }
    // The oldest supported platform and the newest released one. Explicit
    // rather than `recommended()`, which reaches for versions the download
    // site does not serve yet.
    pluginVerification {
        ides {
            create(IntelliJPlatformType.IntellijIdeaCommunity, providers.gradleProperty("platformVersion").get())
            create(IntelliJPlatformType.IntellijIdeaCommunity, providers.gradleProperty("verifyPlatformVersion").get())
        }
    }
    publishing {
        token = providers.environmentVariable("JETBRAINS_MARKETPLACE_TOKEN")
    }
    signing {
        certificateChain = providers.environmentVariable("JETBRAINS_CERTIFICATE_CHAIN")
        privateKey = providers.environmentVariable("JETBRAINS_PRIVATE_KEY")
        password = providers.environmentVariable("JETBRAINS_PRIVATE_KEY_PASSWORD")
    }
}

tasks {
    test {
        useJUnitPlatform()
    }
    // Which build this is, answered by the build rather than by reading
    // properties: the release workflow greps this line.
    register("buildInfo") {
        doLast { println("Tokitoki build: release=$release server=$baseUrl dataDir=~/$dataDir") }
    }
}
